sap.ui.define(
		
	function() {
		"use strict";
		return  {
		errorData :[
		"NOTEXIST",
		"NOHUPARAMETER",
		"MATINFORETRIEVE",
		"TO_LINES_NE_LEIN_LINES",
		"INTERNAL_ERROR",
		"SU_IS_LOCKED",
		"BIN_IS_LOCKED",
		"WRONG_WHS_ID",
		"NO_AUTHORITY",
		"TO_IS_LOCKED",
		"TO_IS_CONFIRMED",
		"TR_IS_LOCKED",
		"PSCH_IS_LOCKED",
		"DLVR_IS_LOCKED",
		"MORE_THAN1_TOS",
		"NOTHING_TO_CONFIRM",
		"OTHERERROR",
		"NO_2STEP",
		"WRONG_CONF_PARAMS",
		"SYSTEM_ERROR",
		"TRANSACTION_ERROR"
		]
			
			};

	});